export * from './cadastro-cliente/cadastro-cliente.component';
export * from './contato-cliente/contato-cliente.component';
export * from './contratacao-fixo/contratacao-fixo.component';
export * from './detalhe-passeios-cliente/detalhe-passeios-cliente.component';
export * from './detalhe-passeios-fixo/detalhe-passeios-fixo.component';
export * from './index-cliente/index-cliente.component';
export * from './login-cliente/login-cliente.component';
export * from './passeios-anteriores/passeios-anteriores.component';
export * from './perfil-cliente/perfil-cliente.component';