version: '3.9'

services:

  wanderlust-postgres:
    image: mathgunz16/wanderlust-postgres:latest
    restart: always
    container_name: wanderlust-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1234
    networks:
      - backend

  wanderlust:
    image: mathgunz16/wanderlust:latest
    ports:
      - 3000:3000
    depends_on:
      - wanderlust-postgres
    networks:
      - backend

  front:
    build:
      context: ../../front-end/wanderlust-angular
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - 80:80 
    networks:
      backend:

networks:
  backend: